### ISSUE TITLE
graph.png missing from the repo

### ISSUE THREAD

**Issue by Ambrevar** [robert-strandh/CLOS-MOP-HTML#9]
It's on the website, but not included here: http://metamodular.com/CLOS-MOP/graph.png

**Comment by Hexstream** [comment]
Also see [my improved version](https://clos-mop.hexstreamsoft.com/classes/#class-graph-section), based on that initial version.

**Comment by robert-strandh** [comment]
I don't understand what the problem is supposed to be.  The link works for me.

**Comment by Ambrevar** [comment]
The graph.png file is missing from this repository: https://github.com/robert-strandh/CLOS-MOP-HTML

**Comment by robert-strandh** [comment]
Ah, yes, I see.  Better yet, I included the FIG source for it.  The PNG is generated
from the FIG source.
